import os

from google.cloud import dialogflow
import pyaudio


def detect_intent_texts(project_id, session_id, texts, language_code):
    """Returns the result of detect intent with texts as inputs.

    Using the same `session_id` between requests allows continuation
    of the conversation."""

    # Activate the session
    session_client = dialogflow.SessionsClient.from_service_account_json("robotarm-315611-becfd47d7bf3.json")

    session = session_client.session_path(project_id, session_id)
    print("Session path: {}\n".format(session))

    # Process the text input
    for text in texts:
        text_input = dialogflow.TextInput(text=text, language_code=language_code)

        query_input = dialogflow.QueryInput({"text": text_input})

        request = dialogflow.DetectIntentRequest({"session": session, "query_input": query_input})

        response = session_client.detect_intent(
            request=request
        )

        print("=" * 20)
        print("Query text: {}".format(response.query_result.query_text))
        print(
            "Detected intent: {} (confidence: {})\n".format(
                response.query_result.intent.display_name,
                response.query_result.intent_detection_confidence,
            )
        )
        print("Fulfillment text: {}\n".format(response.query_result.fulfillment_text))


class Chatbot(object):
    # Set the buffer size and sampling rate for the audio
    CHUNK = 4096
    RATE = 16000

    def __init__(self, project_id, session_id, language_code):
        """
        Initialise the Chatbot
        :param project_id: Google project id
        :param session_id: Create a session id to store the chat info for the session
        :param language_code: Set the language for this session
        """
        # Get credentials
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = \
            "C:\\Users\\edmon\\Desktop\\github\\SoftArmControl\\Chatbot\\robotarm-315611-becfd47d7bf3.json"
        # Set the project config for the chatbot
        
        self.project_id = project_id
        self.session_id = session_id
        self.language_code = language_code
        self.encoding = dialogflow.OutputAudioEncoding.OUTPUT_AUDIO_ENCODING_LINEAR_16
        self.session_client = dialogflow.SessionsClient()
        self.session = self.session_client.session_path(self.project_id, self.session_id)
        self.p = pyaudio.PyAudio()
        self.frames = []

    def get_requests(self):
        """
        Generator function for streaming audio request
        :return:
        """

        # Set input and output audio configuration
        audio_config = dialogflow.InputAudioConfig(
            audio_encoding=self.encoding,
            language_code=self.language_code,
            sample_rate_hertz=self.RATE,
        )

        output_audio_config = dialogflow.OutputAudioConfig(
            audio_encoding=self.encoding,
            sample_rate_hertz=self.RATE
        )

        query_input = dialogflow.QueryInput({"audio_config": audio_config})

        # The first request contains the configuration.
        yield dialogflow.StreamingDetectIntentRequest(
            {"session": self.session, "query_input": query_input, "output_audio_config": output_audio_config}
        )

        # Send audio date chunks to google cloud
        yield dialogflow.StreamingDetectIntentRequest({"input_audio": self.frames})

    def get_user_intent_audio(self, frames):
        """
        Detect user intent from streaming audio input
        :param frames: List of buffers containing audio input
        :return: tuple with query text, response text, intent, intent probability
        """

        # Get responses generated by google cloud
        self.frames = frames
        responses = self.session_client.streaming_detect_intent(self.get_requests())
        query_result = None
        for response in responses:
            # If query result is populated then this element is the query response message
            if response.query_result.fulfillment_text is not "":
                # Save the query response
                query_result = response.query_result

        # Last response message is the audio so it can be played
        self.play_response(response)

        return [query_result.query_text, query_result.fulfillment_text, query_result.intent.display_name,
                query_result.intent_detection_confidence]

    def get_user_intent_text(self, texts):
        """
        Get intent from text input
        :param texts: List of strings containing text
        :return: tuple containing response text, intent, intent probability
        """
        # Iterate over the text input
        for text in texts:
            # Set the input confguration
            text_input = dialogflow.TextInput(text=text, language_code=self.language_code)

            query_input = dialogflow.QueryInput({"text": text_input})

            output_audio_config = dialogflow.OutputAudioConfig(
                audio_encoding=self.encoding,
                sample_rate_hertz=self.RATE
            )

            request = dialogflow.DetectIntentRequest({"session": self.session, "query_input": query_input,
                                                      "output_audio_config": output_audio_config})

            # Get response
            response = self.session_client.detect_intent(
                request=request
            )

            # Play the text to speech from google cloud
            self.play_response(response)

            return [response.query_result.fulfillment_text, response.query_result.intent.display_name,
                    response.query_result.intent_detection_confidence]

    def play_response(self, response):
        """
        Play audio buffer using pyaudio
        :param response: audio buffer (bytes)
        :return: None
        """

        # Open audio output stream (default output device)
        stream = self.p.open(format=pyaudio.paInt16,
                             channels=1,
                             rate=self.RATE,
                             output=True)

        # Write audio data to output stream
        stream.write(response.output_audio)
